### ISSUE TITLE
chrome syncs auth code across devices

### ISSUE THREAD

**Issue by vogler** [drakeapps/synccit-browser-extension#11]
If I change the auth code on device A, it will sync the same code to device B.
Probably should use storage.local instead of storage.sync [here](https://github.com/drakeapps/synccit-browser-extension/blob/chrome-extension/synccit.user.js#L24) 😄 
It would be nice to keep the sync (in case local storage is cleared), but I guess there's no way to see which device one is currently on.

**Comment by vogler** [comment]
BTW: am I right to assume that the auth code is also the reason why synccit doesn't work between my two chrome instances?

**Comment by drakeapps** [comment]
Hmm, this might actually seem more like a feature people would want. Your device would really just be all Chrome devices, which seems fine and makes it a bunch easier to use.

Though adding the option to turn it on/off might be good.

But, it should work across multiple devices with the same auth code. Tracking isn't handled/tracked by auth code, it's really more just of a way of authenticating without having to use your password everywhere.

If you can, send me a screenshot of your JS console while on a reddit page to the email at the bottom of the site: https://synccit.com/

**Comment by vogler** [comment]
> more like a feature people would want

👍 

Just checked again: works fine. The problem was/is that links loaded via RES's infinite scrolling aren't updated.
